<?php

return [
    'MERCADOPAGO_CLIENT_ID'=>env('MERCADOPAGO_CLIENT_ID', ''),
    'MERCADOPAGO_CLIENT_SECRET'=>env('MERCADOPAGO_CLIENT_SECRET', ''),
    'MERCADOPAGO_MP_SANDBOXMODE'=>env('MERCADOPAGO_MP_SANDBOXMODE', ''),
];